### ISSUE TITLE
Bloquear route

### ISSUE THREAD

**Issue by borellaster** [waldemarnt/building-testable-nodejs-api#5]
Olá, em primeiro lugar gostaria de agradecer pelo excelente trabalho da API e vídeos. Eu tenho um projeto aqui(utilizando PostgreSQL/PostGIS e SequelizeJS, porém minha estrutura é um pouco diferente. Eu consegui fazer funcionar a parte de autenticação, conforme demonstrado no vídeo 15, consigo enviar o user e senha, e a API me retorna o token, porém estou com um problema. 

Minha route:
`app.get('/api/countries/:page/:size', countries.findAll);`

Eu até tentei colocar no segundo parâmetro algo próximo ao que você usa na sua API
`app.auth.authenticate()`

porém sem sucesso, a API continua liberada. Será que você pode me dar uma luz?

Obrigado
Felipe

**Comment by borellaster** [comment]
Olá
Coloquei isso:
`app.get('/api/v1/countries/:page/:size', app.auth.authenticate(), countries.findAll);`
Consegui o "Unauthorized"

Ao tentar acessar a url:
http://localhost:8000/api/v1/countries/1/10 passando um parametro no header
Key = `token`
Value = `iLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEifQ.4Dva1HTs.....`

Ele continua aparecendo "Unauthorized" :(


Obrigado
Felipe

**Comment by borellaster** [comment]
Baaa consegui

Tem que ser:
`Authorization: JWT xxxx`

Valeu mesmo assim

Abraço

**Comment by waldemarnt** [comment]
@borellaster isso 💃

**Comment by borellaster** [comment]
Boa noite,
Vou aproveitar o mesmo post pra tirar uma dúvida, pegando do teu próprio exemplo, books. Digamos que meu software seja utilizando por inúneros usuário, cada usuário possui seus próprios books, dentro do books, eu teria um campo user_id. Qual a melhor forma de ter a certeza que juntamente com o token, eu saiba que esse registro realmente pertence ao usuário correto. Com o meu token eu poderia deletar ou alterar qualquer registro na API. Espero que eu tenha me explicado direito.

Qualquer ajuda é bem vinda.

Obrigado desde já

Felipe
