### ISSUE TITLE
Any plans to translate the videos in English?

### ISSUE THREAD

**Issue by vangelov** [waldemarnt/building-testable-nodejs-api#7]
Hello!
I don't know any Portuguese but your code organisation is great! Do you plan to translate your series in English? I think it will help a lot of people.

**Comment by waldemarnt** [comment]
Hey Buddy, Yep, I have plans. The next video series will be based on my book which is https://leanpub.com/construindo-apis-testaveis-com-nodejs/ maybe next month I'll start publishing it.
Please, subscribe in my channel to get involved, as soon as I have some content I'll start publishing it. My main goal was to help the Brazilian community but right now I'll create content in english as well.

Thanks!

**Comment by vangelov** [comment]
Great, thank you!
